---
# tasks file for docker-server
- name: install packages
  apt:
    name: *
    state: latest
    update_cache: yes 

- name: install packages
  apt:
    name: "{{ item }}"
  loop:
    - apt-transport-https 
    - ca-certificates curl 
    - software-properties-common 
    - curl
    - gnupg
    - lsb-release

- name: add Docker GPG
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_version }} stable
    state: present

- name: update and install Docker packages
  apt:
    name: "{{ item }}"
    update_cache: yes 
  loop:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: docker user
  ansible.builtin.user:
    name: docker
    comment: Docker service account
    group: docker


- name: Docker autostart
  ansible.builtin.systemd:
    state: restarted
    enabled: yes
    masked: no
    name: "{{ item }}"
  loop:
    - docker-ce
    - containerd
